### ISSUE TITLE
Package.JSON files missing

### ISSUE THREAD

**Issue by PavanAnanthSharma** [ilavisharma/Asset-Tracker-Blockchain#2]
This is a general concern which you should be concerned about and have the minimal sense to add the package.json file which contains scripts and required dependency for the project, and @ilavisharma PLEASE RECONSIDER YOURSELF BEING A CODER

**Comment by ilavisharma** [comment]
I WIIL SURELY RECONSIDER, THANKS FOR THE SUUGESTION

P.S.
This project is browser based, it does not need node to run so there is no need for a package.json file.
Also before pointing out anything in someone's project, please at least try to explore the project a little bit super smart developer...

**Comment by ilavisharma** [comment]
Plus, forgot to mention fun fact, I'm a dev at Polygon so I'm pretty sure I know (better than you atleast) about what I'm doing.

Cheers man!
Have a good one...
